name: qinfo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - ipykernel
  - pytest
  - sympy
  - numba
  - networkx
  - tqdm
  - pip
  - pip:
      - qiskit
      - qiskit-aer